# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "nokogiri", "~>1.5"
gem "sequel", "~>3.44"
gem "tnetstring", "~>0.3"
gem "yajl-ruby", "~>1.0"
gem "trollop", "~>2.0"
gem "sysexits", "~>1.1"
gem "zmq", "~>2.1"
gem "loggability", "~>0.5"
gem "sqlite3", "~>1.3"

gem "hoe-mercurial", "~>1.4.0", :group => [:development, :test]
gem "hoe-highline", "~>0.1.0", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "configurability", "~>2.0", :group => [:development, :test]
gem "simplecov", "~>0.7", :group => [:development, :test]
gem "hoe-deveiate", "~>0.3", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe", "~>3.7", :group => [:development, :test]

# vim: syntax=ruby
